export const reducercases = {
    SET_TOKEN : "SET_TOKEN",
    SET_PLAYLISTS:"SET_PLAYLISTS",
    SET_USER:"SET_USER",
    SET_SELECTEDPLAYLISTS:"SET_PLAYLISTS",
    SET_CURRENTPLAYING:"SET_CURRENTPLAYING"
}